version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: asset_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asset_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./prisma/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  mysql_data: 